[package]
name = "smart_road"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
tinyfiledialogs = "3.9.0"

sdl2 = { version = "0.36.0", features = ["image", "ttf"] }

[[bin]]
name = "smart_road"
path = "src/main.rs"